name: Leet Code Run Pytest

on:
  push:
    branches:
      - main

jobs:
  run-unit-test:
    runs-on: [ self-hosted, Linux, X64 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install requirements
        run: python3 -m pip install -r requirements.txt

      - name: run pytest
        run: python3 -m pytest
